// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSdqmB8K0pqkDs7Ns-xMVrUf8xpsdeVjY',
    appId: '1:758501778551:web:b3dfbb0f9e2de1bde05272',
    messagingSenderId: '758501778551',
    projectId: 'safetynet-78a92',
    authDomain: 'safetynet-78a92.firebaseapp.com',
    storageBucket: 'safetynet-78a92.appspot.com',
    measurementId: 'G-FV04H49999',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDokkE2AARq8Hyvbu5Ivu-jkmWuFRq-7to',
    appId: '1:758501778551:android:a3960f01244f2a55e05272',
    messagingSenderId: '758501778551',
    projectId: 'safetynet-78a92',
    storageBucket: 'safetynet-78a92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdjrIEG1zjTUcWm6RwN8rdy3zbwccBlU',
    appId: '1:758501778551:ios:dffddf71dbe58ee1e05272',
    messagingSenderId: '758501778551',
    projectId: 'safetynet-78a92',
    storageBucket: 'safetynet-78a92.appspot.com',
    iosBundleId: 'com.example.safetynet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTdjrIEG1zjTUcWm6RwN8rdy3zbwccBlU',
    appId: '1:758501778551:ios:dffddf71dbe58ee1e05272',
    messagingSenderId: '758501778551',
    projectId: 'safetynet-78a92',
    storageBucket: 'safetynet-78a92.appspot.com',
    iosBundleId: 'com.example.safetynet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSdqmB8K0pqkDs7Ns-xMVrUf8xpsdeVjY',
    appId: '1:758501778551:web:afc5c4a5c0c67b4ae05272',
    messagingSenderId: '758501778551',
    projectId: 'safetynet-78a92',
    authDomain: 'safetynet-78a92.firebaseapp.com',
    storageBucket: 'safetynet-78a92.appspot.com',
    measurementId: 'G-CLP4MW9N2Q',
  );
}
